<?php

namespace ContainerX0x9hxT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActualityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jRpHZrV.App\Entity\Actuality' shared service.
     *
     * @return \App\Entity\Actuality
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.jRpHZrV": it references class "App\\Entity\\Actuality" but no such service exists.');
    }
}
