<?php

namespace Container2v0oatN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WNnAIXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wNnA_IX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wNnA_IX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'animal' => ['privates', '.errored..service_locator.wNnA_IX.App\\Entity\\Animals', NULL, 'Cannot autowire service ".service_locator.wNnA_IX": it references class "App\\Entity\\Animals" but no such service exists.'],
        ], [
            'animal' => 'App\\Entity\\Animals',
        ]);
    }
}
