<?php

namespace Container2v0oatN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QXFIQBdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QXFIQBd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QXFIQBd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\ActualityController::delete' => ['privates', '.service_locator.jRpHZrV', 'get_ServiceLocator_JRpHZrVService', true],
            'App\\Controller\\Admin\\ActualityController::edit' => ['privates', '.service_locator.jRpHZrV', 'get_ServiceLocator_JRpHZrVService', true],
            'App\\Controller\\Admin\\ActualityController::index' => ['privates', '.service_locator.oQbgOwk', 'get_ServiceLocator_OQbgOwkService', true],
            'App\\Controller\\Admin\\ActualityController::show' => ['privates', '.service_locator.jRpHZrV', 'get_ServiceLocator_JRpHZrVService', true],
            'App\\Controller\\AnimalsController::delete' => ['privates', '.service_locator.wNnA_IX', 'get_ServiceLocator_WNnAIXService', true],
            'App\\Controller\\AnimalsController::edit' => ['privates', '.service_locator.wNnA_IX', 'get_ServiceLocator_WNnAIXService', true],
            'App\\Controller\\AnimalsController::index' => ['privates', '.service_locator.tiqJ56.', 'get_ServiceLocator_TiqJ56_Service', true],
            'App\\Controller\\AnimalsController::show' => ['privates', '.service_locator.wNnA_IX', 'get_ServiceLocator_WNnAIXService', true],
            'App\\Controller\\DefaultController::animalFound' => ['privates', '.service_locator.tiqJ56.', 'get_ServiceLocator_TiqJ56_Service', true],
            'App\\Controller\\DefaultController::animalMissing' => ['privates', '.service_locator.tiqJ56.', 'get_ServiceLocator_TiqJ56_Service', true],
            'App\\Controller\\DefaultController::index' => ['privates', '.service_locator.tiqJ56.', 'get_ServiceLocator_TiqJ56_Service', true],
            'App\\Controller\\DefaultController::show' => ['privates', '.service_locator.wNnA_IX', 'get_ServiceLocator_WNnAIXService', true],
            'App\\Controller\\DefaultController::showTrouve' => ['privates', '.service_locator.wNnA_IX', 'get_ServiceLocator_WNnAIXService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\Admin\\ActualityController:delete' => ['privates', '.service_locator.jRpHZrV', 'get_ServiceLocator_JRpHZrVService', true],
            'App\\Controller\\Admin\\ActualityController:edit' => ['privates', '.service_locator.jRpHZrV', 'get_ServiceLocator_JRpHZrVService', true],
            'App\\Controller\\Admin\\ActualityController:index' => ['privates', '.service_locator.oQbgOwk', 'get_ServiceLocator_OQbgOwkService', true],
            'App\\Controller\\Admin\\ActualityController:show' => ['privates', '.service_locator.jRpHZrV', 'get_ServiceLocator_JRpHZrVService', true],
            'App\\Controller\\AnimalsController:delete' => ['privates', '.service_locator.wNnA_IX', 'get_ServiceLocator_WNnAIXService', true],
            'App\\Controller\\AnimalsController:edit' => ['privates', '.service_locator.wNnA_IX', 'get_ServiceLocator_WNnAIXService', true],
            'App\\Controller\\AnimalsController:index' => ['privates', '.service_locator.tiqJ56.', 'get_ServiceLocator_TiqJ56_Service', true],
            'App\\Controller\\AnimalsController:show' => ['privates', '.service_locator.wNnA_IX', 'get_ServiceLocator_WNnAIXService', true],
            'App\\Controller\\DefaultController:animalFound' => ['privates', '.service_locator.tiqJ56.', 'get_ServiceLocator_TiqJ56_Service', true],
            'App\\Controller\\DefaultController:animalMissing' => ['privates', '.service_locator.tiqJ56.', 'get_ServiceLocator_TiqJ56_Service', true],
            'App\\Controller\\DefaultController:index' => ['privates', '.service_locator.tiqJ56.', 'get_ServiceLocator_TiqJ56_Service', true],
            'App\\Controller\\DefaultController:show' => ['privates', '.service_locator.wNnA_IX', 'get_ServiceLocator_WNnAIXService', true],
            'App\\Controller\\DefaultController:showTrouve' => ['privates', '.service_locator.wNnA_IX', 'get_ServiceLocator_WNnAIXService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\Admin\\ActualityController::delete' => '?',
            'App\\Controller\\Admin\\ActualityController::edit' => '?',
            'App\\Controller\\Admin\\ActualityController::index' => '?',
            'App\\Controller\\Admin\\ActualityController::show' => '?',
            'App\\Controller\\AnimalsController::delete' => '?',
            'App\\Controller\\AnimalsController::edit' => '?',
            'App\\Controller\\AnimalsController::index' => '?',
            'App\\Controller\\AnimalsController::show' => '?',
            'App\\Controller\\DefaultController::animalFound' => '?',
            'App\\Controller\\DefaultController::animalMissing' => '?',
            'App\\Controller\\DefaultController::index' => '?',
            'App\\Controller\\DefaultController::show' => '?',
            'App\\Controller\\DefaultController::showTrouve' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\ActualityController:delete' => '?',
            'App\\Controller\\Admin\\ActualityController:edit' => '?',
            'App\\Controller\\Admin\\ActualityController:index' => '?',
            'App\\Controller\\Admin\\ActualityController:show' => '?',
            'App\\Controller\\AnimalsController:delete' => '?',
            'App\\Controller\\AnimalsController:edit' => '?',
            'App\\Controller\\AnimalsController:index' => '?',
            'App\\Controller\\AnimalsController:show' => '?',
            'App\\Controller\\DefaultController:animalFound' => '?',
            'App\\Controller\\DefaultController:animalMissing' => '?',
            'App\\Controller\\DefaultController:index' => '?',
            'App\\Controller\\DefaultController:show' => '?',
            'App\\Controller\\DefaultController:showTrouve' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
