<?php

namespace Container2v0oatN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnimalsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wNnA_IX.App\Entity\Animals' shared service.
     *
     * @return \App\Entity\Animals
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.wNnA_IX": it references class "App\\Entity\\Animals" but no such service exists.');
    }
}
