<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEXVF5Mg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEXVF5Mg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEXVF5Mg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEXVF5Mg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEXVF5Mg\App_KernelDevDebugContainer([
    'container.build_hash' => 'EXVF5Mg',
    'container.build_id' => '495a303d',
    'container.build_time' => 1613831432,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEXVF5Mg');
